Project/myDjangoPrj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from product import views

router = routers.DefaultRouter()
router.register(r'tests', views.itemViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('product/', include('product.urls')),
    path('', include('main_pages.urls')),
    path('accounts/', include('allauth.urls')),
    path('drf/', include(router.urls)),
    path('markdownx/', include('markdownx.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Project/product/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ItemList.as_view()),
    path('<int:pk>/', views.ItemDetail.as_view()),
    path('<int:pk>/new_comment/', views.new_comment),
    path('update_comment/<int:pk>/', views.CommentUpdate.as_view()),
    path('delete_comment/<int:pk>/', views.delete_comment),
    path('create_item/', views.ItemCreate.as_view()),
    path('update_item/<int:pk>/', views.ItemUpdate.as_view()),
    path('category/<str:slug>/', views.category_page),
    path('company/<str:slug>/', views.company_page),
    path('tag/<str:slug>/', views.tag_page),
    path('search/<str:q>/', views.ItemSearch.as_view()),

]

Project/product/models.py
from django.contrib.auth.models import User
from django.db import models
from markdownx.models import MarkdownxField
from markdownx.utils import markdown

# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=20, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/product/tag/{self.slug}/'


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/product/category/{self.slug}/'

    class Meta:
        verbose_name_plural = 'Catogories'

class Company(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    address = models.CharField(max_length=50, unique=True, null=True, blank=True)

    number = models.CharField(max_length=50, unique=True, null=True)

    email = models.EmailField(max_length=32, null=True)


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/product/company/{self.slug}/'

    class Meta:
        verbose_name_plural = 'Companies'


class Item(models.Model):
    title = models.CharField(max_length=35)
    content = MarkdownxField()

    head_image = models.ImageField(upload_to='blog/images/%Y/%m/%d/', blank=True)

    price = models.PositiveIntegerField(null=True)

    company = models.ForeignKey(Company, null=True, blank=True, on_delete=models.SET_NULL)
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)

    tags = models.ManyToManyField(Tag, blank=True)

    nutrient = models.TextField(null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return f'/product/{self.pk}/'

    def get_content_markdown(self):
        return markdown(self.content)


class Comment(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    content = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.author} : {self.content} '

    def get_absolute_url(self):
        return f'{self.item.get_absolute_url()}#comment-{self.pk}'

    def get_avatar_url(self):
        if self.author.socialaccount_set.exists():
            return self.author.socialaccount_set.first().get_avatar_url()
        else:
            return 'https://dummyimage.com/50x50/ced4da/6c757d.jpg'

Project/product/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content', )

Project/product/views.py
from datetime import timezone

from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.text import slugify
from django.views.generic import ListView, CreateView, UpdateView, DetailView
from .models import Item, Category, Tag, Comment, Company
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .forms import CommentForm
from rest_framework import viewsets
from .serializers import itemSerializer

# Create your views here.
class itemViewSet(viewsets.ModelViewSet):
    queryset = Item.objects.all()
    serializer_class = itemSerializer

def delete_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    item = comment.item
    if request.user.is_authenticated and request.user == comment.author:
        comment.delete()
        return redirect(item.get_absolute_url())
    else:
        PermissionDenied

class ItemUpdate(LoginRequiredMixin, UpdateView):
    model = Item
    fields = ['title', 'content', 'head_image', 'price', 'company', 'category', 'nutrient']
    template_name = 'product/item_update_form.html'

    def dispatch(self, request, *args, **kwargs):
        current_user = self.request.user
        if current_user.is_authenticated:
            return super(ItemUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated and (current_user.is_superuser or current_user.is_staff):
            form.instance.author = current_user
            response = super(ItemUpdate, self).form_valid(form)
            tags_str = self.request.POST.get('tags_str')
            if tags_str:
                tags_str = tags_str.strip()
                tags_str = tags_str.replace(',', ';')
                tag_list = tags_str.split(';')
                for t in tag_list:
                    t = t.strip()
                    tag, is_tag_created = Tag.objects.get_or_create(name=t)
                    if is_tag_created:
                        tag.slug = slugify(t, allow_unicode=True)
                        tag.save()
                    self.object.tags.add(tag)
            return response
        else:
            return redirect('/product/')

    def get_context_data(self, **kwargs):
        context = super(ItemUpdate, self).get_context_data()
        context['companies'] = Company.objects.all()
        return context


class ItemCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Item
    fields = ['title', 'content', 'head_image', 'price', 'company', 'category', 'nutrient']

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated and (current_user.is_superuser or current_user.is_staff):
            form.instance.author = current_user
            response = super(ItemCreate, self).form_valid(form)
            tags_str = self.request.POST.get('tags_str')

            if tags_str:
                tags_str = tags_str.strip()
                tags_str = tags_str.replace(',', ';')
                tag_list = tags_str.split(';')
                for t in tag_list:
                    t = t.strip()
                    tag, is_tag_created = Tag.objects.get_or_create(name=t)
                    if is_tag_created:
                        tag.slug = slugify(t, allow_unicode=True)
                        tag.save()
                    self.object.tags.add(tag)
            return response

        else:
            return redirect('/product/')

    def get_context_data(self, **kwargs):
        context = super(ItemCreate, self).get_context_data()
        context['companies'] = Company.objects.all()
        return context


class ItemList(ListView):
    model = Item
    ordering = '-pk'
    paginate_by = 6

    def get_context_data(self,  **kwargs):
        context = super(ItemList, self).get_context_data()
        context['companies'] = Company.objects.all()
        return context


class ItemSearch(ItemList):
    paginate_by = None

    def get_queryset(self):
        q = self.kwargs['q']
        item_list = Item.objects.filter(Q(title__contains=q) | Q(tags__name__contains=q)).distinct()
        return item_list

    def get_context_data(self, **kwargs):
        context = super(ItemSearch, self).get_context_data()
        q = self.kwargs['q']
        context['search_info'] = f'Search: {q} ({self.get_queryset().count()})'
        return context


class ItemDetail(DetailView):
    model = Item

    def get_context_data(self, **kwargs):
        context = super(ItemDetail, self).get_context_data()
        context['companies'] = Company.objects.all()
        context['comment_form'] = CommentForm
        return context


class CommentList(ListView):
    model = Comment


def new_comment(request, pk):
    if request.user.is_authenticated:
        item = get_object_or_404(Item, pk=pk)

        if request.method == 'POST':
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.item = item
                comment.author = request.user
                comment.save()
                return redirect(comment.get_absolute_url())
        else:
            return redirect(item.get_absolute_url())
    else:
        raise PermissionDenied


class CommentUpdate(LoginRequiredMixin, UpdateView):
    model = Comment
    form_class = CommentForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(CommentUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied


def category_page(request, slug):
    category = Category.objects.get(slug=slug)
    item_list = Item.objects.filter(category=category)
    return render(request, 'product/item_list.html', {
        'category': category,
        'item_list': item_list,
        'categories': Category.objects.all()
    })


def company_page(request, slug):
    company = Company.objects.get(slug=slug)
    item_list = Item.objects.filter(company=company)
    return render(request, 'product/item_list.html', {
        'category': company,
        'item_list': item_list,
        'companies': Company.objects.all()
    })




def tag_page(request, slug):
    tag = Tag.objects.get(slug=slug)
    item_list = tag.item_set.all()
    return render(request, 'product/item_list.html', {
        'tag': tag,
        'item_list': item_list,
        'categories': Category.objects.all(),
    })

Project/product/templates/product/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block head_title %} Items {% endblock %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" href="{% static 'product/bootstrap4/css/bootstrap.min.css' %}" type="text/css" media="screen"/>
        <script src="https://kit.fontawesome.com/67e2221e3b.js" crossorigin="anonymous"></script>
    </head>
    <body>
        <!-- Responsive navbar-->
        {% include 'product/navbar.html' %}

        <!-- Header-->

        <section class="pt-4">
            <div class="container px-lg-5">
                <div class="row">
                    <div class="col-md-9 col-lg-10" id="main-area">
                    {% block main_area %}
                    {% endblock %}
                    </div>

                    <div class="col-md-3 col-lg-2">
                      {% include 'product/sidebar.html' %}
                    </div>
                </div>
            </div>
        </section>




        <!-- Footer-->
        {% include 'product/footer.html' %}

        <!-- Bootstrap core JS-->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

    </body>
</html>

Project/product/templates/product/comment_form.html
{% extends 'product/base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
    Edit Comment - BLOG
{% endblock %}

{% block main_area %}
  <h1>Edit Comment</h1>
  <hr/>
  <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <table>
          {{form | crispy}}

      </table>
      <br>
      <button type="submit" class="btn btn-primary float-right">Submit</button>
      <br>
      <br>
      <br>
  </form>

{% endblock %}

Project/product/templates/product/comment_list.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'product/bootstrap4/css/bootstrap.min.css' %}" type="text/css" media="screen"/>
    <title>About_me</title>
    <link href="{% static 'main_pages/css/about.css' %}" rel="stylesheet" type="text/css" media="screen"/>
    <script src="https://kit.fontawesome.com/67e2221e3b.js" crossorigin="anonymous"></script>
    <script type="text/javascript", src="https://www.gstatic.com/charts/loader.js"></script>
  </head>
  <body>
  {% include 'product/navbar.html' %}


    <section>
        <div class="container">
            <div class="row justify-content-between">
                <div class="col-lg-5  text-light" id="main-area">

                    {% if comment_list.exists %}
                    {% for c in comment_list %}
                    <div>{{ c.content }}</div>
                    {% endfor %}
                    {% endif %}

                </div>
            </div>
        </div>
    </section>


    <div>{% include 'product/footer.html' %}</div>


    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
  </body>
</html>

Project/product/templates/product/footer.html
<footer class="py-5 bg-dark">
  <div class="container text-light" >
    <p>서울지사: 서울특별시 송파구 밥원로 97길, Y비지스니센터</p>
    <p>TEL: 1234-5678 | e-mail: coffeeshop@coffeeshop@coffee.com</p>
  </div>
</footer>

Project/product/templates/product/item_detail.html
{% extends 'product/base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
    {{item.title}} - BLOG
{% endblock %}

{% block main_area %}

    <body>
        <!-- Page Content-->
        <div class="container px-4 px-lg-5">
            {% if user.is_authenticated %}
                {% if user.is_superuser or user.is_staff %}
                    <a class="btn text-white float-right" style="background-color:#4B3621" href="/product/update_item/{{item.pk}}/" role="button">
                        <i class="fas fa-pen"> UPDATE ITEM</i>
                    </a>
                {% endif %}
            {% endif %}

            <br>

            <!-- Heading Row-->
            <div class="row gx-4 gx-lg-5 align-items-center my-5">
                {% if item.head_image %}
                <div class="col-lg-6"><img class="img-fluid rounded mb-4 mb-lg-0" src="{{ item.head_image.url }}" alt="..." /></div>
                {% endif %}
                <div class="col-lg-6">
                    {% if item.category %}
                        <h3>
                            <a href="{{item.category.get_absolute_url}}" class="badge badge-secondary" style="margin-bottom:20px;">{{ item.category }}</a>
                            {% if item.company %}
                            <a href="{{item.company.get_absolute_url}}" class="badge badge-secondary" style="margin-bottom:20px;">{{ item.company }}</a>
                            {% endif %}
                        </h3>
                    {% endif %}

                    <h1 class="font-weight-light">{{item.title}}</h1>
                    <p>{{item.get_content_markdown | safe}}</p>
                    <p>{{item.price}}원</p>

                    {% if item.tags.exists %}
                        {% for t in item.tags.iterator %}
                        <span class="badge badge-pill badge-light">
                        <a href="{{t.get_absolute_url}}" style="color:#4B3621">
                            {{t}}
                        </a>
                        </span>
                        {% endfor %}
                    {% endif %}

                    <hr>
                    <p>{{item.nutrient}}</p>
                </div>
            </div>

            <!-- Comments section-->
                    <div id="comment-area" class="mb-5">
                        <div class="card bg-light">
                            <div class="card-body">
                                <!-- Comment form-->
                                    {% if user.is_authenticated %}
                                    <form class="mb-4" id="comment-form" method="post" action="{{item.get_absolute_url}}new_comment/">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            {{comment_form | crispy}}
                                        </div>
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    </form>
                                    {% else %}
                                        <a role="button" class="btn btn-dark btn-block btn-sm" href="#" data-toggle="modal" data-target="#loginModal">
                                            Log in and Leave a comment
                                        </a>
                                    {% endif %}


                                {% if item.comment_set.exists %}
                                {% for comment in item.comment_set.iterator %}
                                <!-- Single comment-->
                                <div class="media d-flex" id="comment-{{comment.pk}}">
                                    <img class="rounded-circle mr-3" src="{{comment.get_avatar_url}}" alt="{{comment.author}}" width="60px"/>
                                    <div class="media-body ms-3">
                                        {% if user.is_authenticated and comment.author == user %}
                                            <div class="float-right">
                                                <a role="button" class="btn btn-sm btn-info float-right"
                                                   href="/product/update_comment/{{comment.pk}}/">
                                                    Edit
                                                </a>
                                                <a role="button" class="btn btn-sm btn-danger float-right"
                                                   data-toggle="modal" data-target="#deleteModal-{{comment.pk}}"
                                                   href="#">
                                                    Delete
                                                </a>
                                            </div>

                                        <!-- Modal -->
                                            <div
                                              class="modal fade"
                                              id="deleteModal-{{comment.pk}}"
                                              tabindex="-1"
                                              aria-labelledby="exampleModalLabel"
                                              aria-hidden="true"
                                            >
                                              <div class="modal-dialog">
                                                <div class="modal-content">
                                                  <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">Are you sure?</h5>
                                                    <button
                                                      type="button"
                                                      class="close"
                                                      data-dismiss="modal"
                                                      aria-label="Close"
                                                    >
                                                      <span aria-hidden="true">&times;</span>
                                                    </button>
                                                  </div>
                                                  <div class="modal-body">
                                                    <del>{{comment | linebreaks}}</del>
                                                  </div>
                                                  <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

                                                    <a role="button" class="btn btn-secondary" href="/product/delete_comment/{{comment.pk}}/">
                                                      Delete
                                                    </a>
                                                  </div>
                                                </div>
                                              </div>
                                            </div>


                                        {% endif %}
                                        <div class="fw-bold">
                                            {{comment.author.username}}
                                            <small class="text-muted">{{comment.created_at}}</small>
                                        </div>
                                        <p>{{comment.content | linebreaks}}</p>
                                        {% if comment.created_at != comment.modified_at %}
                                            <p class="text-muted float-right">
                                                <small>Updated : {{comment.modified_at}}</small>
                                            </p>
                                        {% endif %}
                                    </div>
                                </div>
                                {% endfor %}
                                {% endif %}
                            </div>
                        </div>
                    </div>
        </div>
    </body>

{% endblock %}

Project/product/templates/product/item_form.html
{% extends 'product/base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
    Create Items
{% endblock %}

{% block main_area %}

      <h1>Create new items</h1>
      <hr/>
      <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <table>
              {{form | crispy}}

              <div id="div_id_tags_str">
                <label for="id_tags">Tags:</label>
                <input id="id_tags" type="text" name="tags_str" class="textinput textInput form-control">
              </div>
          </table>
          <br>
          <button type="submit" class="btn btn-primary float-right">Submit</button>
          <br>
          <br>
          <br>
      </form>
        {{form.media}}

{% endblock %}

Project/product/templates/product/item_list.html
{% extends 'product/base.html' %}
{% load static %}
{% block main_area %}

<!-- Page Content-->

<section class="pt-4">
    <div class="container px-lg-5">

        {% if user.is_authenticated %}
            {% if user.is_superuser or user.is_staff %}
                <a class="btn text-white float-right" style="background-color:#4B3621" href="/product/create_item/" role="button">
                    <i class="fa-solid fa-pen-to-square"> NEW ITEM</i>
                </a>
            {% endif %}
        {% endif %}

        <h2>ITEMS
            {% if search_info %}
                - <span class="badge">{{search_info}}</span>
            {% endif %}

            {% if category %}
                - <span class="badge">{{category}}</span>
            {% endif %}

            {% if tag %}
                - <span class="badge">{{tag}}</span>
            {% endif %}
        </h2>

        <!-- Page Features-->
        <div class="row gx-lg-5">
            {% if item_list.exists %}
            {% for i in item_list %}
            <div class="col-lg-6 col-xxl-6 mb-6">
                <div class="card bg-light border-0 h-100">
                    <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                        {% if i.category %}
                        <h5>
                            <a href="{{i.category.get_absolute_url}}" class="badge badge-secondary" style="margin-bottom:50px;">{{ i.category }}</a>

                            {% if i.company %}
                            <a href="{{i.company.get_absolute_url}}" class="badge badge-secondary" style="margin-bottom:50px;">{{ i.company }}</a>
                            {% endif %}

                        </h5>
                        {% endif %}



                        {% if i.head_image %}
                        <div class="bg-gradient mb-4 mt-n4"><img class="card-img-top" src="{{ i.head_image.url}}"></div>
                        {% endif %}

                        {% if i.tags.exists %}
                        {% for t in i.tags.iterator %}
                        <span class="badge badge-pill badge-light">
                        <a href="{{t.get_absolute_url}}" style="color:#4B3621">
                            {{t}}
                        </a>
                        </span>
                        {% endfor %}
                        {% endif %}
                        <br>
                        <br>

                        <h4 class="fs-4 fw-bold">{{ i.title }}</h4>
                        <p class="text-muted">{{i.get_content_markdown | truncatewords_html:20 | safe}}</p>
                        <p class="mb-0">{{ i.price }}원</p>
                        <hr>
                        <a class="btn text-white" style="background-color:#4B3621" href="{{i.get_absolute_url}}">More Info →</a>

                    </div>
                </div>
            </div>
            {% endfor %}
            {% endif %}
        </div>


        <!-- Pagination-->
          {% if is_paginated %}
          <nav aria-label="Pagination">
            <hr class="my-0" />
            <ul class="pagination justify-content-center my-4">
                {% if page_obj.has_previous %}
                  <li class="page-item">
                    <a class="page-link" style="color:#4B3621;" href="?page={{page_obj.previous_page_number}}" tabindex="-1" aria-disabled="true"><i class="fa-solid fa-arrow-left"></i></a>
                  </li>
                {% else %}
                  <li class="page-item disabled">
                        <a class="page-link" style="color:#4B3621;" href="#" tabindex="-1" aria-disabled="true"><i class="fa-solid fa-arrow-left"></i></a>
                      </li>
                {% endif %}

                {% if page_obj.has_next %}
                  <li class="page-item">
                    <a class="page-link" style="color:#4B3621;" href="?page={{page_obj.next_page_number}}"><i class="fa-solid fa-arrow-right"></i></a>
                  </li>
                {% else %}
                  <li class="page-item disabled">
                    <a class="page-link" style="color:#4B3621;" href="#!"><i class="fa-solid fa-arrow-right"></i></a>
                  </li>
                {% endif %}
            </ul>
          </nav>
          {% endif %}


    </div>
</section>



{% endblock %}

Project/product/templates/product/item_update_form.html
{% extends 'product/base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
    Update Items
{% endblock %}

{% block main_area %}
  <h1>Update items</h1>
  <hr/>
  <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <table>
          {{form | crispy}}
          <div id="div_id_tags_str">
                <label for="id_tags">Tags:</label>
                <input id="id_tags" type="text" name="tags_str" value="{{tags_str_default}}" class="textinput textInput form-control">
          </div>
      </table>
      <br>
      <button type="submit" class="btn btn-primary float-right">Submit</button>
      <br>
      <br>
      <br>
  </form>
    {{form.media}}
{% endblock %}